### ISSUE TITLE
直接git clone下来的文件夹，导入到androidStudio无法识别为app项目

### ISSUE THREAD

**Issue by SivanCola** [kymjs/EmojiChat#9]
直接git clone该项目到桌面文件夹，导入到Android Studio 3.6.2后，Sync gradle成功后，发现无法识别该项目为android app项目。
截图如下：
![run_log](https://user-images.githubusercontent.com/32437197/78863530-62bf9200-7a6c-11ea-8947-7f019c87e5e3.png)

**Comment by tudoutiaoya** [comment]
为啥没人回答你

**Comment by SivanCola** [comment]
> 为啥没人回答你

哈哈，当年的问题看起来有些低级。我都忘记当年自己提过这个issue了、
